### ISSUE TITLE
`StackOverflow` on `is_timeseries_parameter`

### ISSUE THREAD

**Issue by hexaeder** [SciML/SymbolicIndexingInterface.jl#85]
**Describe the bug 🐞**

According to the docs, you should define
```julia
symbolic_container(indp::MyIndexProvier) = indp
```
in case `MyIndexProvider` implements the interface:

https://github.com/SciML/SymbolicIndexingInterface.jl/blob/e7dd822c3dd5aa60161f77e6e96a32ce5c4941bb/src/index_provider_interface.jl#L2-L7

However, this leads to a stack overflow in the default implementation of  `is_timeseries_parameter`

https://github.com/SciML/SymbolicIndexingInterface.jl/blob/e7dd822c3dd5aa60161f77e6e96a32ce5c4941bb/src/index_provider_interface.jl#L61-L67

as it descents forever as long as the `symbolic_container` method exists.

The docs do not mention any new methods to implement to fulfill the index provider interface.

**Comment by hexaeder** [comment]
Same problem seems to apply to appear in `get_all_timeseries_indexes` now to.

**Comment by AayushSabharwal** [comment]
Thanks for pointing this out, #90 should fix this

**Comment by hexaeder** [comment]
Thanks for the fix, unfortunately the problem still pops up, now in a method in `SciMLBase`.

https://github.com/SciML/SciMLBase.jl/blob/56ba8819c1637fffbae5722057c5532b8d48c21c/src/solutions/ode_solutions.jl#L360-L366

However I removed the `symbolic_container(inpr::MyIndPr) = inpr` definition and everything it seems to work. Maybe this should be reflected in the `symbolic_container` docstring, that the method should not be implemented for types implementing the interface...

https://github.com/SciML/SymbolicIndexingInterface.jl/blob/58e0df3acc973ac31e9d040a4cd8b1e2ad0056db/src/index_provider_interface.jl#L4-L5

**Comment by AayushSabharwal** [comment]
Yeah that does seem like the better approach. It is _technically_ breaking, but we should be able to get away with it.
